version: "3.5"
services:
  ###############################################
  # Development environment
  aioserver:
    image: btc/forecast-server
    # user: "${UID:-1000}"
    # depends_on:
    #   - redis-db
    #   - ts-db
    ports:
      - 8080:8080
    volumes:
      - .:/opt/btc/server
    environment:
      - TS_DB_HOST=ts-db
      # - TS_DB_HOST=ec2-13-236-10-53.ap-southeast-2.compute.amazonaws.com
      - REDIS_DB_HOST=redis-db
    command: python3 app.py

  swagger:
    image: swaggerapi/swagger-editor:v3.6.21
    ports:
      - "80:8080"

